name: Build and Release
on:
  push:
    tags:
      - "*"
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest]
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          cmake --version
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg --version

      - name: Install dependencies on macOS
        if: ${{ (matrix.os == 'macos-latest') || (matrix.os == 'macos-13') }}
        run: |
          brew install cmake
          cmake --version
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg --version

      - name: Install Qt on macOS
        if: ${{ (matrix.os == 'macos-latest') || (matrix.os == 'macos-13') }}
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'

      - name: Install Qt on windows
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Build on macOS
        if: ${{ (matrix.os == 'macos-latest') || (matrix.os == 'macos-13') }}
        run: |
          export
          cmake -S . -B ../build-macos -DCMAKE_BUILD_TYPE:STRING=Release "-DCMAKE_PREFIX_PATH:STRING=${{ github.workspace }}/../Qt/6.7.2/macos"
          cmake --build ../build-macos --target all --config Release

      - name: Package on macOS
        if: ${{ (matrix.os == 'macos-latest') || (matrix.os == 'macos-13') }}
        run: |
          cmake --build ../build-macos --target package --config Release

      - name: Build on windows
        if: matrix.os == 'windows-latest'
        run: |
          cmake -S . -B ../build-windows -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PREFIX_PATH:STRING="${{ github.workspace }}/../Qt/6.7.2/macos"
          cmake --build ../build-windows --target ALL_BUILD --config Release

      - name: Package on windows
        if: matrix.os == 'windows-latest'
        run: |
          cmake --build ../build-windows --target package --config Release

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Release all platforms"
          files: |
            ../build-macos/*.zip
            ../build-windows/*.zip